### ISSUE TITLE
Nix/NixOS

### ISSUE THREAD

**Issue by haruki7049** [Comamoca/sugoi-it#1]
NixNixNixNixNixNix
具体的には、少なくとも`shell.nix`が採用されているプロジェクトでの活用方法。後は`default.nix`でのビルドの方法…とかかな？

**Comment by Comamoca** [comment]
提案ありがとうございます。
題材にNixをとのことですが、自分のNix力が低くわかりやすく解説できる自信がないのと、題材は**これから実務で使う可能性が高そうなもの**を優先して選んでいるので、採用は見送らせていただきます。すみません。

**Comment by haruki7049** [comment]
了解した！　謝らなくても大丈夫やで。　検討頂きありがとう！！
